[package]
name = "pathery"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.58"
aws-config = "0.51.0"
aws-sdk-s3 = "0.21.0"
aws-sdk-sqs = "0.21.0"
aws_lambda_events = "0.7.2"
chrono = "0.4.23"
http = "0.2.8"
lambda_http = { version = "0.7", default-features = false, features = ["apigw_rest"] }
lambda_runtime = "0.7"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tantivy = "0.18.1"
tantivy-common = "0.3.0"
thiserror = "1.0.37"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "std"] }
uuid = "1.2.1"
