[package]
name = "pathery"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
aws-config = "0.51.0"
aws_lambda_events = "0.7.2"
chrono = "0.4.23"
lambda_http = { version = "0.7", default-features = false, features = ["apigw_rest"] }
lambda_runtime = "0.7"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_yaml = "0.9"
tantivy = "0.18.1"
tantivy-common = "0.3.0"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
uuid = "1.2.1"
